[package]
name = "server"
version = "0.1.0"
authors = ["Clouds Flowing <clouds.flowing@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
flexi_logger = "*"
rand = "*"
uuid = "*"
sha2 = "*"
diesel = { git="https://github.com/diesel-rs/diesel", features=["postgres", "uuid", "r2d2"] }
actix-web = "4.0.0-beta.9"
anyhow = "*"
serde = "*"
serde_json = "*"
