[package]
name = "square-core"
version = "0.1.0"
authors = ["Clouds Flowing <clouds.flowing@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
flexi_logger = "*"
async-trait = "*"
anyhow = "*"
rand = "*"
uuid = "*"
sha2 = "*"
diesel = { git="https://github.com/diesel-rs/diesel", features=["postgres", "uuid", "r2d2"] }
axum = { version = "*", features=["headers"] }
tokio = { version = "*", features=["rt-multi-thread"] }
serde = "*"
serde_json = "*"
jsonwebtoken = "*"
headers = "*"
