CREATE TABLE users (
  id BIGINT NOT NULL PRIMARY KEY
    GENERATED BY DEFAULT AS IDENTITY,
  alias TEXT NOT NULL UNIQUE, -- unique username
  name TEXT NOT NULL, -- nickname
  description TEXT,
  avatar TEXT,
  inserted_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE posts (
  topic_id BIGINT NOT NULL,
  id UUID NOT NULL PRIMARY KEY,
  floor INTEGER NOT NULL,
  author_id BIGINT NOT NULL REFERENCES users (id),
  author_name TEXT NOT NULL,
  content INTEGER NOT NULL,
  revision INTEGER NOT NULL DEFAULT 0,
  parent_id UUID REFERENCES posts (id),
  inserted_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
